/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author admin
 */
public class User_Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form User_Dashboard
     */
    public User_Dashboard(int id) {
        initComponents();
        venuePanel.setLayout(new javax.swing.BoxLayout(venuePanel, javax.swing.BoxLayout.Y_AXIS));
        venuePanel.setPreferredSize(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rulesBtn = new javax.swing.JButton();
        signOutbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        profileBtn = new javax.swing.JButton();
        FutsalVenue = new javax.swing.JButton();
        BasketballVenue = new javax.swing.JButton();
        TabletenninsVenue = new javax.swing.JButton();
        CricksalVenue = new javax.swing.JButton();
        BadmintonVenue = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        venuePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 600));
        setSize(new java.awt.Dimension(1400, 600));

        jPanel1.setBackground(new java.awt.Color(26, 60, 52));
        jPanel1.setMaximumSize(new java.awt.Dimension(1600, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 600));

        rulesBtn.setBackground(new java.awt.Color(0, 102, 102));
        rulesBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 14)); // NOI18N
        rulesBtn.setForeground(new java.awt.Color(220, 220, 220));
        rulesBtn.setText("View Rules");
        rulesBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rulesBtn.setBorderPainted(false);
        rulesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesBtnActionPerformed(evt);
            }
        });

        signOutbtn.setBackground(new java.awt.Color(255, 0, 0));
        signOutbtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        signOutbtn.setForeground(new java.awt.Color(220, 220, 220));
        signOutbtn.setText("Sign Out");
        signOutbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        signOutbtn.setBorderPainted(false);
        signOutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutbtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(26, 60, 52));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(134, 117, 117));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(220, 220, 220));
        jLabel1.setText("Welcome to Khelmandu");

        profileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Profilelogo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(338, 338, 338)
                .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FutsalVenue.setBackground(new java.awt.Color(0, 102, 102));
        FutsalVenue.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        FutsalVenue.setForeground(new java.awt.Color(220, 220, 220));
        FutsalVenue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/footballicon.png"))); // NOI18N
        FutsalVenue.setText("Futsal");
        FutsalVenue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        FutsalVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FutsalVenueActionPerformed(evt);
            }
        });

        BasketballVenue.setBackground(new java.awt.Color(0, 102, 102));
        BasketballVenue.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        BasketballVenue.setForeground(new java.awt.Color(220, 220, 220));
        BasketballVenue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Basketballiconl.png"))); // NOI18N
        BasketballVenue.setText("Basketball");
        BasketballVenue.setToolTipText("");
        BasketballVenue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BasketballVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasketballVenueActionPerformed(evt);
            }
        });

        TabletenninsVenue.setBackground(new java.awt.Color(0, 102, 102));
        TabletenninsVenue.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        TabletenninsVenue.setForeground(new java.awt.Color(220, 220, 220));
        TabletenninsVenue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tabletennisicon.png"))); // NOI18N
        TabletenninsVenue.setText("Table Tennis");
        TabletenninsVenue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TabletenninsVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TabletenninsVenueActionPerformed(evt);
            }
        });

        CricksalVenue.setBackground(new java.awt.Color(0, 102, 102));
        CricksalVenue.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        CricksalVenue.setForeground(new java.awt.Color(220, 220, 220));
        CricksalVenue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cricksalicon.png"))); // NOI18N
        CricksalVenue.setText("Cricksal");
        CricksalVenue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        CricksalVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CricksalVenueActionPerformed(evt);
            }
        });

        BadmintonVenue.setBackground(new java.awt.Color(0, 102, 102));
        BadmintonVenue.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        BadmintonVenue.setForeground(new java.awt.Color(220, 220, 220));
        BadmintonVenue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Badminton.png"))); // NOI18N
        BadmintonVenue.setText("Badminton");
        BadmintonVenue.setToolTipText("");
        BadmintonVenue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BadmintonVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BadmintonVenueActionPerformed(evt);
            }
        });

        venuePanel.setBackground(new java.awt.Color(203, 200, 200));
        jScrollPane1.setViewportView(venuePanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(signOutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rulesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BasketballVenue, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(FutsalVenue, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(BadmintonVenue, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(CricksalVenue, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(TabletenninsVenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1047, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(BasketballVenue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(FutsalVenue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(TabletenninsVenue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(CricksalVenue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(BadmintonVenue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(rulesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(signOutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FutsalVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FutsalVenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FutsalVenueActionPerformed

    private void BasketballVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasketballVenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BasketballVenueActionPerformed

    private void TabletenninsVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TabletenninsVenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TabletenninsVenueActionPerformed

    private void CricksalVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CricksalVenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CricksalVenueActionPerformed

    private void BadmintonVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BadmintonVenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BadmintonVenueActionPerformed

    private void rulesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rulesBtnActionPerformed

    private void signOutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signOutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BadmintonVenue;
    private javax.swing.JButton BasketballVenue;
    private javax.swing.JButton CricksalVenue;
    private javax.swing.JButton FutsalVenue;
    private javax.swing.JButton TabletenninsVenue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton profileBtn;
    private javax.swing.JButton rulesBtn;
    private javax.swing.JButton signOutbtn;
    private javax.swing.JPanel venuePanel;
    // End of variables declaration//GEN-END:variables
    
    public javax.swing.JPanel getVenuePanel(){return venuePanel;}
    
    
    public void addBasketballListener(ActionListener listener){
        BasketballVenue.addActionListener(listener);
    }

    public void addCricksalListener(ActionListener listener){
        CricksalVenue.addActionListener(listener);
    }

    public void addFutsalListener(ActionListener listener){
        FutsalVenue.addActionListener(listener);
    }

    public void addTabletennisListener(ActionListener listener){
        TabletenninsVenue.addActionListener(listener);
    }

    public void addBadmintonListener(ActionListener listener){
        BadmintonVenue.addActionListener(listener);
    }
    
    public void profileListener(ActionListener listener){
        profileBtn.addActionListener(listener);
    }
    
    public void rulesListener(ActionListener listener){
        rulesBtn.addActionListener(listener);
    }
    public void SignOutListener(ActionListener listener) {
            signOutbtn.addActionListener(listener);
    }
    

}
